# Learn more at: https://aka.ms/yaml
jobs:
- job: npmRunTest
  pool:
    vmImage: 'Ubuntu 16.04'
    demands: npm

  timeoutInMinutes: 360

  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  
  - script: |
      if [[ $BUILD_REASON == "Schedule" ]]; then git config --global user.email "types@microsoft.com" && git config --global user.name "TypeScript Bot" && npm run update-codeowners; fi
      git checkout -- . && npm run test

    displayName: 'npm run test'
  - script: |
      pwd
      TOKEN='7469b4e94ce21b43e3ab7a'
      TOKEN+='79960c12a1e067f2ec'
      DANGER_GITHUB_API_TOKEN=$TOKEN npx danger ci
    workingDirectory: $HOME
    displayName: 'danger scrape suggestions'
  
trigger:
- master
  